import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { PageHeader, SectionHeading, SourceNote } from "@/components/ui";
import { ProgramExplorer } from "@/components/program-explorer";
import { getSiteData } from "@/lib/store";

export const metadata = { title: "Programs", description: "Discover IET-DSMNRU undergraduate and postgraduate engineering programmes from the published seat matrix." };

export default async function ProgramsPage() { const data = await getSiteData(); return <><PageHeader eyebrow="Academic discovery" title="Programmes with the source attached." description="Compare programme level, duration, approved seat matrix entries and the department behind each record. Admissions rules remain on DSMNRU's official service." breadcrumbs={[{ label: "Programs" }]} /><section className="section"><div className="container"><SectionHeading eyebrow="Programme catalogue" title="Find the right academic route." description="The catalogue is rendered from structured programme records, not hardcoded page copy." /><ProgramExplorer programs={data.programs} /><div style={{ marginTop: 28 }}><SourceNote>Programme titles, durations and approved seats are seeded from Table 1 of the supplied IET-DSMNRU profile PDF. Eligibility and fee rules are intentionally not repeated when not present in that source; use official DSMNRU admissions.</SourceNote></div></div></section><section className="section soft"><div className="container" style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 25, flexWrap: "wrap" }}><div><div className="eyebrow">Next step</div><h2 style={{ marginTop: 9 }}>Application information belongs to DSMNRU.</h2><p className="lead" style={{ fontSize: ".95rem" }}>IET helps you understand the academic offer. The university owns current application windows, eligibility, fees and forms.</p></div><a href="https://dsmru.up.nic.in/main/User/admission_pro.aspx" target="_blank" rel="noreferrer" className="button copper">Official admissions <ArrowUpRight size={16} /></a></div></section></>; }
