import Link from "next/link";
import { ArrowUpRight, Building2, Landmark, ShieldCheck } from "lucide-react";
import { PageHeader, SectionHeading } from "@/components/ui";
import { getSiteData } from "@/lib/store";

export const metadata = { title: "About IET", description: "Learn about IET-DSMNRU, its history, vision, mission and leadership." };

export default async function AboutPage() {
  const data = await getSiteData();
  const page = data.pages.find((item) => item.slug === "about");
  const dean = data.faculty.find((item) => item.slug === "chandra-kumar-dixit");
  return (
    <>
      <PageHeader eyebrow="About IET" title="An engineering faculty with inclusion at its centre." description="Discover the institute's history, academic direction and commitment to inclusion." breadcrumbs={[{ label: "About" }]} />
      <section className="section"><div className="container content-grid"><div>
        <div className="eyebrow">Institutional profile</div><h2>{page?.title || "About IET"}</h2>
        <p className="lead">{page?.body}</p>
        <p>The University was originally established through an ordinance dated 29 August 2008, later formalized by U.P. Act No. 1 of 2009 and further strengthened by U.P. Act No. 24 of 2011. IET was established in 2016 as engineering education expanded within DSMNRU.</p>

      </div><aside className="info-aside"><div className="aside-card"><h3>At a glance</h3><div className="aside-item"><strong>Institute</strong>IET · DSMNRU</div><div className="aside-item"><strong>Established</strong>2016</div><div className="aside-item"><strong>Faculty</strong>Faculty of Engineering &amp; Technology</div><div className="aside-item"><strong>Location</strong>Lucknow, Uttar Pradesh, India</div></div></aside></div></section>

      <section className="section soft"><div className="container"><SectionHeading eyebrow="Direction" title="A faculty shaped by purpose." description="Our vision and mission guide teaching, research and innovation." /><div className="content-grid"><div className="data-card"><div className="eyebrow">Vision</div><h3 style={{ fontSize: "1.65rem", marginTop: 20 }}>Globally competent. Inclusive. Innovation-driven.</h3><p style={{ marginTop: 18 }}>To develop a globally competent, inclusive and innovation-driven technical education ecosystem, where engineering knowledge contributes not only to technological advancement but also to societal empowerment.</p></div><div className="data-card"><div className="eyebrow">Mission</div><h3 style={{ fontSize: "1.65rem", marginTop: 20 }}>Quality education with universal design.</h3><p style={{ marginTop: 18 }}>To provide quality education aligned with AICTE and NEP 2020 guidelines, promote research and innovation, foster entrepreneurship, ensure accessibility through Universal Design, and produce ethically responsible engineers capable of addressing real-world challenges.</p></div></div></div></section>

      <section className="section"><div className="container"><SectionHeading eyebrow="Institutional journey" title="From IET to FoET." description="From five core engineering branches to a broader academic structure." /><div className="timeline"><div className="timeline-item"><span>2008–2011 / University foundation</span><h3>DSMNRU is established through ordinance and state legislation.</h3><p className="small">The founding ordinance was followed by U.P. Act No. 1 of 2009 and U.P. Act No. 24 of 2011.</p></div><div className="timeline-item"><span>2016 / Engineering begins</span><h3>IET is established with five core engineering branches.</h3><p className="small">Computer Science &amp; Engineering, Electrical Engineering, Electronics &amp; Communication Engineering, Mechanical Engineering and Civil Engineering form the original engineering disciplines.</p></div><div className="timeline-item"><span>2017–2020 / Academic base</span><h3>Laboratories, workshops, smart classrooms and faculty capacity are strengthened.</h3><p className="small">Teaching developed towards Outcome-Based Education and later NEP 2020 alignment.</p></div><div className="timeline-item"><span>2021 onward / Emerging domains</span><h3>Computing and interdisciplinary programmes expand.</h3><p className="small">Programmes expanded into AI, AI &amp; ML and Data Science, followed by honours and M.Tech. pathways.</p></div><div className="timeline-item"><span>After 2020 / FoET frame</span><h3>The Faculty of Engineering &amp; Technology becomes an umbrella structure.</h3><p className="small">It brings engineering departments together for governance, interdisciplinary collaboration, research and innovation.</p></div></div></div></section>

      {dean && <section className="section dark"><div className="container content-grid"><div><div className="eyebrow inverse">Leadership</div><h2>Academic leadership</h2><p className="lead">Meet the leadership of the Faculty of Engineering &amp; Technology.</p><Link className="link-arrow" href="/faculty/chandra-kumar-dixit" style={{ color: "var(--lime)" }}>Open leadership profile</Link></div><div className="data-card" style={{ background: "#13263a", borderColor: "#2a4a62", color: "white" }}><Building2 size={30} color="var(--lime)" /><h3 style={{ marginTop: 20 }}>{dean?.name}</h3><p style={{ color: "#b9c7ce" }}>{dean?.designation}</p><p style={{ color: "#b9c7ce", fontSize: ".84rem" }}>{dean?.qualification}</p>{dean?.email && <a href={`mailto:${dean.email}`} style={{ color: "var(--lime)", fontSize: ".82rem" }}>{dean.email}</a>}</div></div></section>}

      <section className="section tight"><div className="container"><div className="ecosystem-grid"><div className="ecosystem-panel"><ShieldCheck size={25} color="var(--copper)" /><h3 style={{ marginTop: 15 }}>Explore IET</h3><p className="small">IET identity, academic units, programme discovery, faculty, laboratories, research, projects, achievements, events, student organisations, resources and institute contact channels.</p><Link href="/resources" className="link-arrow">Explore resources</Link></div><div className="ecosystem-panel"><Landmark size={25} color="var(--copper)" /><h3 style={{ marginTop: 15 }}>University services</h3><p className="small">Find university notices, Samarth, admissions, examinations, results and other services on the DSMNRU website.</p><a href="https://dsmru.up.nic.in/" target="_blank" rel="noreferrer" className="link-arrow">Visit DSMNRU <ArrowUpRight size={14} /></a></div></div></div></section>
    </>
  );
}
