import Link from "next/link";
import { Accessibility, CalendarDays, Trophy, Users } from "lucide-react";
import { PageHeader, SectionHeading } from "@/components/ui";
import { getSiteData } from "@/lib/store";

export const metadata = { title: "Campus life", description: "IET campus life discovery for events, technical activities, organizations and achievements." };

export default async function CampusPage() { const data = await getSiteData(); return <><PageHeader eyebrow="Campus life" title="Campus life" description="Discover student activities, clubs, events, achievements and facilities at IET." breadcrumbs={[{ label: "Campus" }]} /><section className="section"><div className="container"><SectionHeading eyebrow="Discover" title="Choose what you want to follow." /><div className="route-grid"><CampusCard href="/events" icon={<CalendarDays />} title="Events & activities" body={`${data.events.length} events and activities.`} /><CampusCard href="/achievements" icon={<Trophy />} title="Achievements" body={`${data.achievements.length} student and team achievements.`} /><CampusCard href="/organizations" icon={<Users />} title="Organizations" body={`${data.organizations.length} clubs, chapters and student groups.`} /><CampusCard href="/accessibility" icon={<Accessibility />} title="Accessible campus information" body="Website accessibility options and help." /></div></div></section><section className="section dark"><div className="container content-grid"><div><div className="eyebrow inverse">University services</div><h2>Student services at DSMNRU</h2><p className="lead">Find university notices, results, examination forms and the student portal through our official resource links.</p><Link className="link-arrow" href="/resources">University resources</Link></div></div></section></>; }
function CampusCard({ href, icon, title, body }: { href: string; icon: React.ReactNode; title: string; body: string }) { return <Link href={href} className="route-card"><span style={{ color: "var(--copper)" }}>{icon}</span><div><h3>{title}</h3><p>{body}</p></div><span className="link-arrow">Open</span></Link>; }
