import Link from "next/link";
import { Accessibility, CalendarDays, Trophy, Users } from "lucide-react";
import { PageHeader, SectionHeading, SourceNote } from "@/components/ui";
import { getSiteData } from "@/lib/store";

export const metadata = { title: "Campus life", description: "IET campus life discovery for events, technical activities, organizations and achievements." };

export default async function CampusPage() { const data = await getSiteData(); return <><PageHeader eyebrow="Campus life" title="The student experience is a content system too." description="Campus life stays IET-specific: technical activities, chapters, clubs, events, achievements and accessible facilities — added by approved editors." breadcrumbs={[{ label: "Campus" }]} /><section className="section"><div className="container"><SectionHeading eyebrow="Discover" title="Choose what you want to follow." /><div className="route-grid"><CampusCard href="/events" icon={<CalendarDays />} title="Events & activities" body={`${data.events.length} published records · upcoming and past IET programmes.`} /><CampusCard href="/achievements" icon={<Trophy />} title="Achievements" body={`${data.achievements.length} published records · verified student and team outcomes.`} /><CampusCard href="/organizations" icon={<Users />} title="Organizations" body={`${data.organizations.length} published records · clubs, chapters and student groups.`} /><CampusCard href="/accessibility" icon={<Accessibility />} title="Accessible campus information" body="Preferences and content guidance for an inclusive information experience." /></div></div></section><section className="section dark"><div className="container content-grid"><div><div className="eyebrow inverse">IET-specific scope</div><h2>Campus life without recreating the university portal.</h2><p className="lead">Events here are institute activities; notices, results, examination forms and student ERP links remain clearly identified as DSMNRU services.</p></div><SourceNote>No campus event, club or achievement list is asserted without a published CMS record. This page is ready for institutional ownership.</SourceNote></div></section></>; }
function CampusCard({ href, icon, title, body }: { href: string; icon: React.ReactNode; title: string; body: string }) { return <Link href={href} className="route-card"><span style={{ color: "var(--copper)" }}>{icon}</span><div><h3>{title}</h3><p>{body}</p></div><span className="link-arrow">Open</span></Link>; }
