import Link from "next/link";
import { CalendarDays, ExternalLink } from "lucide-react";
import { EmptyState, PageHeader, SectionHeading, SourceNote } from "@/components/ui";
import { getSiteData } from "@/lib/store";

export const metadata = { title: "Events & activities", description: "Discover IET workshops, seminars, conferences, hackathons and student activities." };

export default async function EventsPage() { const data = await getSiteData(); const upcoming = data.events.filter((event) => event.startsAt && new Date(event.startsAt) >= new Date()); const past = data.events.filter((event) => !upcoming.includes(event)); return <><PageHeader eyebrow="Campus life" title="An IET event record, not a notice replacement." description="Workshops, seminars, conferences, hackathons, guest lectures and student activities can live here. University notices remain on DSMNRU." breadcrumbs={[{ label: "Events" }]} /><section className="section"><div className="container"><SectionHeading eyebrow="Upcoming" title="What is on the calendar." />{upcoming.length ? <div className="data-grid">{upcoming.map((event) => <EventCard key={event.id} event={event} />)}</div> : <EmptyState title="No upcoming IET events are published" description="An authorized IET editor can create an event record with dates, location, registration link and accessible gallery media." />}<div style={{ marginTop: 35 }}><SectionHeading eyebrow="Past activities" title="The institutional memory." />{past.length ? <div className="data-grid">{past.map((event) => <EventCard key={event.id} event={event} />)}</div> : <EmptyState title="No past IET events are published" description="The event archive will grow from approved IET records, not copied university notices." />}</div><div style={{ marginTop: 28 }}><SourceNote>No event record is inferred from the supplied IET profile PDF. Use the CMS to publish only approved IET-specific events.</SourceNote></div></div></section><section className="section soft"><div className="container" style={{ display: "flex", alignItems: "center", gap: 24, justifyContent: "space-between", flexWrap: "wrap" }}><div><div className="eyebrow">University notices</div><h2 style={{ marginTop: 9 }}>Looking for a DSMNRU notice?</h2><p className="lead" style={{ fontSize: ".95rem" }}>Use the system that owns university-wide notifications.</p></div><a className="button" href="https://dsmru.up.nic.in/main/User/Notices.aspx" target="_blank" rel="noreferrer">Official notices <ExternalLink size={15} /></a></div></section></>; }

function EventCard({ event }: { event: import("@/lib/types").EventItem }) { return <div className="data-card"><CalendarDays size={23} color="var(--copper)" /><h3>{event.title}</h3><p>{event.summary}</p>{event.startsAt && <p className="small">{new Date(event.startsAt).toLocaleDateString("en-IN", { dateStyle: "medium" })}{event.location ? ` · ${event.location}` : ""}</p>}{event.registrationUrl && <a href={event.registrationUrl} target="_blank" rel="noreferrer" className="link-arrow">Registration <ExternalLink size={14} /></a>}</div>; }
